# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html spring\u914D\u7F6E\u7684\u6587\u6863
server:
  port: 8081

swagger:
  host: localhost
  enable: true

spring:
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

  servlet:
    multipart:
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
  #  kafka:
  #   bootstrap-servers: 192.168.99.100:9092
  #   consumer:
  #     group-id: default
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    minIdle: 30
    maxActive: 500
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testOnBorrow: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.188.45:3306/spring_boot_work_cloud?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8&useAffectedRows=true
    username: root
    password: ROOT
#  #redis集群
#  redis:
#    host: 192.168.0.12
#    port: 6379
#    password: Yongqi88@
#    timeout: 20000
#      #    集群环境打开下面注释，单机不需要打开
#      #    cluster:
#      #      集群信息
#      #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#      #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#    #      maxRedirects: 3
mybatis:
  #  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zbb.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
csr:
  password: 1

address: http://htt.nat100.top


uiteld: 2029003
appld: 51136
suiteKey: suitevffa4znrajet6tbe
suiteSecret: dazd4gfqlgfAV92HA52MG2F5hsxIChwsvft2J41IZS8LWOy8vHuOaR1JHypy!
token: 3fd9383a735547da935366d